theme: jekyll-theme-cayman
title: Gemstone.Diagnostics
description: GPA Gemstone Diagnostics Library
github:
  repository_name: gemstone/diagnostics
  owner_url: https://www.gridprotectionalliance.org
  owner_name: Grid Protection Alliance
plugins:
  - jemoji
